/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TradingHoursRouteImport } from './routes/trading-hours'
import { Route as NewsRouteImport } from './routes/news'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as HeatMapsRouteImport } from './routes/heat-maps'
import { Route as CotReportRouteImport } from './routes/cot-report'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CotReportIndexRouteImport } from './routes/cot-report.index'

const TradingHoursRoute = TradingHoursRouteImport.update({
  id: '/trading-hours',
  path: '/trading-hours',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const HeatMapsRoute = HeatMapsRouteImport.update({
  id: '/heat-maps',
  path: '/heat-maps',
  getParentRoute: () => rootRouteImport,
} as any)
const CotReportRoute = CotReportRouteImport.update({
  id: '/cot-report',
  path: '/cot-report',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CotReportIndexRoute = CotReportIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CotReportRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/cot-report': typeof CotReportRouteWithChildren
  '/heat-maps': typeof HeatMapsRoute
  '/journal': typeof JournalRoute
  '/news': typeof NewsRoute
  '/trading-hours': typeof TradingHoursRoute
  '/cot-report/': typeof CotReportIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/heat-maps': typeof HeatMapsRoute
  '/journal': typeof JournalRoute
  '/news': typeof NewsRoute
  '/trading-hours': typeof TradingHoursRoute
  '/cot-report': typeof CotReportIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/cot-report': typeof CotReportRouteWithChildren
  '/heat-maps': typeof HeatMapsRoute
  '/journal': typeof JournalRoute
  '/news': typeof NewsRoute
  '/trading-hours': typeof TradingHoursRoute
  '/cot-report/': typeof CotReportIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/cot-report'
    | '/heat-maps'
    | '/journal'
    | '/news'
    | '/trading-hours'
    | '/cot-report/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/heat-maps'
    | '/journal'
    | '/news'
    | '/trading-hours'
    | '/cot-report'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/cot-report'
    | '/heat-maps'
    | '/journal'
    | '/news'
    | '/trading-hours'
    | '/cot-report/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  CotReportRoute: typeof CotReportRouteWithChildren
  HeatMapsRoute: typeof HeatMapsRoute
  JournalRoute: typeof JournalRoute
  NewsRoute: typeof NewsRoute
  TradingHoursRoute: typeof TradingHoursRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trading-hours': {
      id: '/trading-hours'
      path: '/trading-hours'
      fullPath: '/trading-hours'
      preLoaderRoute: typeof TradingHoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heat-maps': {
      id: '/heat-maps'
      path: '/heat-maps'
      fullPath: '/heat-maps'
      preLoaderRoute: typeof HeatMapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cot-report': {
      id: '/cot-report'
      path: '/cot-report'
      fullPath: '/cot-report'
      preLoaderRoute: typeof CotReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cot-report/': {
      id: '/cot-report/'
      path: '/'
      fullPath: '/cot-report/'
      preLoaderRoute: typeof CotReportIndexRouteImport
      parentRoute: typeof CotReportRoute
    }
  }
}

interface CotReportRouteChildren {
  CotReportIndexRoute: typeof CotReportIndexRoute
}

const CotReportRouteChildren: CotReportRouteChildren = {
  CotReportIndexRoute: CotReportIndexRoute,
}

const CotReportRouteWithChildren = CotReportRoute._addFileChildren(
  CotReportRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  CotReportRoute: CotReportRouteWithChildren,
  HeatMapsRoute: HeatMapsRoute,
  JournalRoute: JournalRoute,
  NewsRoute: NewsRoute,
  TradingHoursRoute: TradingHoursRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
