/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TradingHoursRouteImport } from './routes/trading-hours'
import { Route as NewsRouteImport } from './routes/news'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as HeatMapsRouteImport } from './routes/heat-maps'
import { Route as CotReportRouteImport } from './routes/cot-report'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CotReportIndexRouteImport } from './routes/cot-report.index'
import { Route as IndicesSp500RouteImport } from './routes/indices.sp500'
import { Route as IndicesRussellRouteImport } from './routes/indices.russell'
import { Route as IndicesNasdaq100RouteImport } from './routes/indices.nasdaq100'
import { Route as IndicesDow30RouteImport } from './routes/indices.dow30'
import { Route as CotReportSlugRouteImport } from './routes/cot-report.$slug'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const TradingHoursRoute = TradingHoursRouteImport.update({
  id: '/trading-hours',
  path: '/trading-hours',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const HeatMapsRoute = HeatMapsRouteImport.update({
  id: '/heat-maps',
  path: '/heat-maps',
  getParentRoute: () => rootRouteImport,
} as any)
const CotReportRoute = CotReportRouteImport.update({
  id: '/cot-report',
  path: '/cot-report',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CotReportIndexRoute = CotReportIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CotReportRoute,
} as any)
const IndicesSp500Route = IndicesSp500RouteImport.update({
  id: '/indices/sp500',
  path: '/indices/sp500',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicesRussellRoute = IndicesRussellRouteImport.update({
  id: '/indices/russell',
  path: '/indices/russell',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicesNasdaq100Route = IndicesNasdaq100RouteImport.update({
  id: '/indices/nasdaq100',
  path: '/indices/nasdaq100',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicesDow30Route = IndicesDow30RouteImport.update({
  id: '/indices/dow30',
  path: '/indices/dow30',
  getParentRoute: () => rootRouteImport,
} as any)
const CotReportSlugRoute = CotReportSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CotReportRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/cot-report': typeof CotReportRouteWithChildren
  '/heat-maps': typeof HeatMapsRoute
  '/journal': typeof JournalRoute
  '/mcp': typeof McpRoute
  '/news': typeof NewsRoute
  '/trading-hours': typeof TradingHoursRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/cot-report/$slug': typeof CotReportSlugRoute
  '/indices/dow30': typeof IndicesDow30Route
  '/indices/nasdaq100': typeof IndicesNasdaq100Route
  '/indices/russell': typeof IndicesRussellRoute
  '/indices/sp500': typeof IndicesSp500Route
  '/cot-report/': typeof CotReportIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/heat-maps': typeof HeatMapsRoute
  '/journal': typeof JournalRoute
  '/mcp': typeof McpRoute
  '/news': typeof NewsRoute
  '/trading-hours': typeof TradingHoursRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/cot-report/$slug': typeof CotReportSlugRoute
  '/indices/dow30': typeof IndicesDow30Route
  '/indices/nasdaq100': typeof IndicesNasdaq100Route
  '/indices/russell': typeof IndicesRussellRoute
  '/indices/sp500': typeof IndicesSp500Route
  '/cot-report': typeof CotReportIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/cot-report': typeof CotReportRouteWithChildren
  '/heat-maps': typeof HeatMapsRoute
  '/journal': typeof JournalRoute
  '/mcp': typeof McpRoute
  '/news': typeof NewsRoute
  '/trading-hours': typeof TradingHoursRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/cot-report/$slug': typeof CotReportSlugRoute
  '/indices/dow30': typeof IndicesDow30Route
  '/indices/nasdaq100': typeof IndicesNasdaq100Route
  '/indices/russell': typeof IndicesRussellRoute
  '/indices/sp500': typeof IndicesSp500Route
  '/cot-report/': typeof CotReportIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/cot-report'
    | '/heat-maps'
    | '/journal'
    | '/mcp'
    | '/news'
    | '/trading-hours'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/cot-report/$slug'
    | '/indices/dow30'
    | '/indices/nasdaq100'
    | '/indices/russell'
    | '/indices/sp500'
    | '/cot-report/'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/heat-maps'
    | '/journal'
    | '/mcp'
    | '/news'
    | '/trading-hours'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/cot-report/$slug'
    | '/indices/dow30'
    | '/indices/nasdaq100'
    | '/indices/russell'
    | '/indices/sp500'
    | '/cot-report'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/cot-report'
    | '/heat-maps'
    | '/journal'
    | '/mcp'
    | '/news'
    | '/trading-hours'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/cot-report/$slug'
    | '/indices/dow30'
    | '/indices/nasdaq100'
    | '/indices/russell'
    | '/indices/sp500'
    | '/cot-report/'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  CotReportRoute: typeof CotReportRouteWithChildren
  HeatMapsRoute: typeof HeatMapsRoute
  JournalRoute: typeof JournalRoute
  McpRoute: typeof McpRoute
  NewsRoute: typeof NewsRoute
  TradingHoursRoute: typeof TradingHoursRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  IndicesDow30Route: typeof IndicesDow30Route
  IndicesNasdaq100Route: typeof IndicesNasdaq100Route
  IndicesRussellRoute: typeof IndicesRussellRoute
  IndicesSp500Route: typeof IndicesSp500Route
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trading-hours': {
      id: '/trading-hours'
      path: '/trading-hours'
      fullPath: '/trading-hours'
      preLoaderRoute: typeof TradingHoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heat-maps': {
      id: '/heat-maps'
      path: '/heat-maps'
      fullPath: '/heat-maps'
      preLoaderRoute: typeof HeatMapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cot-report': {
      id: '/cot-report'
      path: '/cot-report'
      fullPath: '/cot-report'
      preLoaderRoute: typeof CotReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cot-report/': {
      id: '/cot-report/'
      path: '/'
      fullPath: '/cot-report/'
      preLoaderRoute: typeof CotReportIndexRouteImport
      parentRoute: typeof CotReportRoute
    }
    '/indices/sp500': {
      id: '/indices/sp500'
      path: '/indices/sp500'
      fullPath: '/indices/sp500'
      preLoaderRoute: typeof IndicesSp500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indices/russell': {
      id: '/indices/russell'
      path: '/indices/russell'
      fullPath: '/indices/russell'
      preLoaderRoute: typeof IndicesRussellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indices/nasdaq100': {
      id: '/indices/nasdaq100'
      path: '/indices/nasdaq100'
      fullPath: '/indices/nasdaq100'
      preLoaderRoute: typeof IndicesNasdaq100RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indices/dow30': {
      id: '/indices/dow30'
      path: '/indices/dow30'
      fullPath: '/indices/dow30'
      preLoaderRoute: typeof IndicesDow30RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cot-report/$slug': {
      id: '/cot-report/$slug'
      path: '/$slug'
      fullPath: '/cot-report/$slug'
      preLoaderRoute: typeof CotReportSlugRouteImport
      parentRoute: typeof CotReportRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CotReportRouteChildren {
  CotReportSlugRoute: typeof CotReportSlugRoute
  CotReportIndexRoute: typeof CotReportIndexRoute
}

const CotReportRouteChildren: CotReportRouteChildren = {
  CotReportSlugRoute: CotReportSlugRoute,
  CotReportIndexRoute: CotReportIndexRoute,
}

const CotReportRouteWithChildren = CotReportRoute._addFileChildren(
  CotReportRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  CotReportRoute: CotReportRouteWithChildren,
  HeatMapsRoute: HeatMapsRoute,
  JournalRoute: JournalRoute,
  McpRoute: McpRoute,
  NewsRoute: NewsRoute,
  TradingHoursRoute: TradingHoursRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  IndicesDow30Route: IndicesDow30Route,
  IndicesNasdaq100Route: IndicesNasdaq100Route,
  IndicesRussellRoute: IndicesRussellRoute,
  IndicesSp500Route: IndicesSp500Route,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
